# Generated by Django 3.1.6 on 2022-03-18 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_member_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document_author_abstract',
            name='author',
        ),
        migrations.AddField(
            model_name='document_author',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document_author_abstract',
            name='document_author',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='application.document_author'),
            preserve_default=False,
        ),
    ]
