# Generated by Django 3.1.6 on 2022-03-23 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20220318_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='year_term',
        ),
    ]
