# Generated by Django 3.1.6 on 2022-03-23 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_document_year_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='remarks',
        ),
    ]
