# Generated by Django 3.1.6 on 2022-03-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_remove_document_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='series_no',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
