# Generated by Django 3.1.6 on 2022-03-23 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20220323_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_author',
            field=models.ManyToManyField(blank=True, to='application.Document_Author'),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_enacted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
