# Generated by Django 3.1.6 on 2022-03-23 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20220323_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_author',
        ),
        migrations.AlterField(
            model_name='document_author_abstract',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='application.document'),
        ),
    ]
