# Generated by Django 3.1.6 on 2022-03-23 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20220323_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document_author_abstract',
            name='document_author',
        ),
        migrations.AddField(
            model_name='document_author_abstract',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document_author_abstract',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.document'),
        ),
    ]
