# Generated by Django 3.1.6 on 2022-03-24 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20220323_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document_author',
            name='is_active',
        ),
        migrations.AddField(
            model_name='document',
            name='date_approved',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='document',
            name='remarks',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
