# Generated by Django 3.1.6 on 2022-03-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_auto_20220326_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_type',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
